

print("Entrer un nombre e1 :")
a = int(input())
print("Entrer un nombre e2 :")
b = int(input())

def Resultat_reste(CHIFFRE_A_DIVISER, RESTE_A_DIVISER, RESULTAT, RESTE_NEXT):
	RESULTAT_TEMPORAIRE = CHIFFRE_A_DIVISER - RESTE_A_DIVISER
	COMPTEUR = 1
	while RESULTAT_TEMPORAIRE > RESTE_A_DIVISER:
		RESULTAT_TEMPORAIRE = RESULTAT_TEMPORAIRE - RESTE_A_DIVISER
		COMPTEUR += 1
	RESULTAT.append(COMPTEUR)
	RESTE_NEXT.append(RESULTAT_TEMPORAIRE)
	return ([RESULTAT], RESTE_NEXT)


if (a < b):
	print("Mieux vaut tenter l'inverse")
else:
#On descend
	c = []
	d = [0]
	CHIFFRE_A_DIVISER = []
	RESTE_A_DIVISER = []
	RESULTAT = []
	RESTE_NEXT = []

	#Init
	CHIFFRE_A_DIVISER.append(a)
	RESTE_A_DIVISER.append(b)
	Resultat_reste(CHIFFRE_A_DIVISER[-1], RESTE_A_DIVISER[-1], RESULTAT, RESTE_NEXT)
	

	while RESTE_NEXT[-1] != 1:
		if RESTE_NEXT[-1] == 0:
			print("a et b ne sont pas premiers entre eux")
			break
		CHIFFRE_A_DIVISER.append(RESTE_A_DIVISER[-1])
		RESTE_A_DIVISER.append(RESTE_NEXT[-1])
		Resultat_reste(CHIFFRE_A_DIVISER[-1], RESTE_A_DIVISER[-1], RESULTAT, RESTE_NEXT)

	#On remonte
	COMPTEUR_REMONTE = 2
	MULTIPLICATEUR_GAUCHE = 1
	MULTIPLICATEUR_DROITE = -RESULTAT[-1]
	RESULTAT_REMONTE = []
	#Init
	RESULTAT_REMONTE.append([RESTE_NEXT[-1], CHIFFRE_A_DIVISER[-1], MULTIPLICATEUR_GAUCHE, RESTE_A_DIVISER[-1], MULTIPLICATEUR_DROITE])

	while COMPTEUR_REMONTE <= len(CHIFFRE_A_DIVISER):
		if (list(str(COMPTEUR_REMONTE))[-1] in ['0','2','4','6','8']):
			MULTIPLICATEUR_GAUCHE = MULTIPLICATEUR_GAUCHE + (MULTIPLICATEUR_DROITE * -RESULTAT[-COMPTEUR_REMONTE])
			RESULTAT_REMONTE.append([RESTE_NEXT[-1], CHIFFRE_A_DIVISER[-(COMPTEUR_REMONTE - 1)], MULTIPLICATEUR_GAUCHE, CHIFFRE_A_DIVISER[-COMPTEUR_REMONTE], MULTIPLICATEUR_DROITE])
		else:
			MULTIPLICATEUR_DROITE = MULTIPLICATEUR_DROITE + (MULTIPLICATEUR_GAUCHE * -RESULTAT[-COMPTEUR_REMONTE])
			RESULTAT_REMONTE.append([RESTE_NEXT[-1], CHIFFRE_A_DIVISER[-(COMPTEUR_REMONTE)], MULTIPLICATEUR_GAUCHE, CHIFFRE_A_DIVISER[-(COMPTEUR_REMONTE - 1)], MULTIPLICATEUR_DROITE])
		COMPTEUR_REMONTE += 1

	RESTE_NEXT

	print(CHIFFRE_A_DIVISER)
	print(RESTE_A_DIVISER)
	print(RESULTAT)
	print(RESTE_NEXT)
	print(RESULTAT_REMONTE)
	if RESULTAT_REMONTE[-1][2] < RESULTAT_REMONTE[-1][4]*-1:
		print("U = " + str(RESULTAT_REMONTE[-1][2]) + " & V = " + str(RESULTAT_REMONTE[-1][4]))
	else:
		print("U = " + str(RESULTAT_REMONTE[-1][4]) + " & V = " + str(RESULTAT_REMONTE[-1][2]))

input()